apiVersion: v1
kind: Service
metadata:
  name: recommendation
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: recommendation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: recommendation
    version: virtualized
  name: recommendation-virtualized
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
      version: virtualized
  template:
    metadata:
      labels:
        app: recommendation
        version: virtualized
      annotations:
        sidecar.istio.io/inject: 'true'   
    spec:
      containers:
      - env:
        image: abdennebi/recommendation:virtual
        args: ["-import=/go/bin/simulation.json"]
        imagePullPolicy: IfNotPresent
        name: recommendation
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        securityContext:
          privileged: false
